// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartActions from "./islands/AddToCartActions.tsx";
import * as $AddToCartButton from "./islands/AddToCartButton.tsx";
import * as $Debug from "./islands/Debug.tsx";
import * as $HeaderButton from "./islands/HeaderButton.tsx";
import * as $HeaderModals from "./islands/HeaderModals.tsx";
import * as $HeaderSearchbar from "./islands/HeaderSearchbar.tsx";
import * as $HeroSection from "./islands/HeroSection.tsx";
import * as $HeroVideoCarroussel from "./islands/HeroVideoCarroussel.tsx";
import * as $ModalImage from "./islands/ModalImage.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $NewsletterModal from "./islands/NewsletterModal.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductButtonFloatingText from "./islands/ProductButtonFloatingText.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SearchResultsGridChoice from "./islands/SearchResultsGridChoice.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Sort from "./islands/Sort.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartActions.tsx": $AddToCartActions,
    "./islands/AddToCartButton.tsx": $AddToCartButton,
    "./islands/Debug.tsx": $Debug,
    "./islands/HeaderButton.tsx": $HeaderButton,
    "./islands/HeaderModals.tsx": $HeaderModals,
    "./islands/HeaderSearchbar.tsx": $HeaderSearchbar,
    "./islands/HeroSection.tsx": $HeroSection,
    "./islands/HeroVideoCarroussel.tsx": $HeroVideoCarroussel,
    "./islands/ModalImage.tsx": $ModalImage,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/NewsletterModal.tsx": $NewsletterModal,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductButtonFloatingText.tsx": $ProductButtonFloatingText,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SearchResultsGridChoice.tsx": $SearchResultsGridChoice,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Sort.tsx": $Sort,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
